/* ============================================================
   DATA.JS — Marie Kids con FOTOS REALES de tu catálogo
   Generado automáticamente desde https://navemed.github.io/catalogo-marie-kids/
   Todas las categorías: vestidos, jeans, conjuntos, casacas, invierno, niño
   ============================================================ */

const PRODUCTS = [
  {
    id: "mk-001",
    slug: "vestido-chaleco-gris--chaqueta-corta--boina",
    name: "Vestido Chaleco Gris & Chaqueta Corta & Boina",
    category: "vestidos",
    ageGroup: ["12-18M"],
    season: "todo-el-año",
    price: 49,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 21,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12-18M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Chaleco%20Gris%20%26%20Chaqueta%20Corta%20%26%20Boina.jpg"],
    description: "Vestido Chaleco Gris & Chaqueta Corta & Boina - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-002",
    slug: "vestido-fiesta-bautizo-rosa-claro",
    name: "Vestido Fiesta Bautizo Rosa Claro",
    category: "vestidos",
    ageGroup: ["12-18M"],
    season: "todo-el-año",
    price: 49,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 22,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12-18M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Fiesta%20Bautizo%20Rosa%20Claro.jpg"],
    description: "Vestido Fiesta Bautizo Rosa Claro - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-003",
    slug: "vestido-princesa-bebe-gala-rosa",
    name: "Vestido Princesa Bebé Gala Rosa",
    category: "vestidos",
    ageGroup: ["18-24M"],
    season: "todo-el-año",
    price: 49,
    oldPrice: 69,
    badge: "oferta",
    rating: 4.8,
    reviews: 23,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["18-24M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Princesa%20Beb%C3%A9%20Gala%20Rosa.jpg"],
    description: "Vestido Princesa Bebé Gala Rosa - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-004",
    slug: "vestido-uso-diario-rosa-12-18m",
    name: "Vestido Uso Diario Rosa 12-18M",
    category: "vestidos",
    ageGroup: ["12-18M"],
    season: "todo-el-año",
    price: 39,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 24,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12-18M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Uso%20Diario%20Rosa%2012-18M.jpg"],
    description: "Vestido Uso Diario Rosa 12-18M - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-005",
    slug: "vestido-lazo-rosa-cremita",
    name: "Vestido Lazo Rosa Cremita",
    category: "vestidos",
    ageGroup: ["18-24M"],
    season: "todo-el-año",
    price: 39,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 25,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["18-24M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Lazo%20Rosa%20Cremita.jpg"],
    description: "Vestido Lazo Rosa Cremita - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-006",
    slug: "vestido-uso-diario-rojo-2-anos",
    name: "Vestido Uso Diario Rojo 2 Años",
    category: "vestidos",
    ageGroup: ["2"],
    season: "todo-el-año",
    price: 45,
    oldPrice: 65,
    badge: "oferta",
    rating: 4.8,
    reviews: 26,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Uso%20Diario%20Rojo%202%20A%C3%B1os.jpg"],
    description: "Vestido Uso Diario Rojo 2 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-007",
    slug: "vestido-flores-blanco--lila-3-anos",
    name: "Vestido Flores Blanco & Lila 3 Años",
    category: "vestidos",
    ageGroup: ["3"],
    season: "todo-el-año",
    price: 49,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 27,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["3"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Flores%20Blanco%20%26%20Lila%203%20A%C3%B1os.jpg"],
    description: "Vestido Flores Blanco & Lila 3 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-008",
    slug: "vestido-tutu-celeste-3-anos",
    name: "Vestido Tutú Celeste 3 Años",
    category: "vestidos",
    ageGroup: ["3"],
    season: "todo-el-año",
    price: 49,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 28,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["3"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Tut%C3%BA%20Celeste%203%20A%C3%B1os.jpg"],
    description: "Vestido Tutú Celeste 3 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-009",
    slug: "vestido-rosa-flores-3d-lentejuela-5-anos",
    name: "Vestido Rosa Flores 3D Lentejuela 5 Años",
    category: "vestidos",
    ageGroup: ["5"],
    season: "todo-el-año",
    price: 49,
    oldPrice: 69,
    badge: "oferta",
    rating: 4.8,
    reviews: 29,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["5"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Rosa%20Flores%203D%20Lentejuela%205%20A%C3%B1os.jpg"],
    description: "Vestido Rosa Flores 3D Lentejuela 5 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-010",
    slug: "vestido-blanco-encaje-lazo-saten-5-anos",
    name: "Vestido Blanco Encaje Lazo Satén 5 Años",
    category: "vestidos",
    ageGroup: ["5"],
    season: "todo-el-año",
    price: 49,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 30,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["5"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Blanco%20Encaje%20Lazo%20Sat%C3%A9n%205%20A%C3%B1os.jpg"],
    description: "Vestido Blanco Encaje Lazo Satén 5 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-011",
    slug: "vestido-rosa-brillos-princesa-6-anos",
    name: "Vestido Rosa Brillos Princesa 6 Años",
    category: "vestidos",
    ageGroup: ["6"],
    season: "todo-el-año",
    price: 39,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 31,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["6"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Vestido%20Rosa%20Brillos%20Princesa%206%20A%C3%B1os.jpg"],
    description: "Vestido Rosa Brillos Princesa 6 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-012",
    slug: "conjunto-denim-cerezas-12-18m",
    name: "Conjunto Denim Cerezas 12-18M",
    category: "jeans",
    ageGroup: ["12-18M"],
    season: "todo-el-año",
    price: 45,
    oldPrice: 65,
    badge: "nuevo",
    rating: 4.8,
    reviews: 32,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12-18M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%20Denim%20Cerezas%2012-18M.jpg"],
    description: "Conjunto Denim Cerezas 12-18M - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-013",
    slug: "chompa--jean-con-lazo-12-18m",
    name: "Chompa & Jean con Lazo 12-18M",
    category: "jeans",
    ageGroup: ["12-18M"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 33,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12-18M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Chompa%20%26%20Jean%20con%20Lazo%2012-18M.jpg"],
    description: "Chompa & Jean con Lazo 12-18M - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-014",
    slug: "set-trio-cherry-love-jean-bow-18-24m",
    name: "Set Trío Cherry Love Jean Bow 18-24M",
    category: "jeans",
    ageGroup: ["18-24M"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 34,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["18-24M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Set%20Tr%C3%ADo%20Cherry%20Love%20Jean%20Bow%2018-24M.jpg"],
    description: "Set Trío Cherry Love Jean Bow 18-24M - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-015",
    slug: "top-cuello-alto--jean-cargo-2-anos",
    name: "Top Cuello Alto & Jean Cargo 2 Años",
    category: "jeans",
    ageGroup: ["2"],
    season: "todo-el-año",
    price: 45,
    oldPrice: 65,
    badge: "oferta",
    rating: 4.8,
    reviews: 35,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Top%20Cuello%20Alto%20%26%20Jean%20Cargo%202%20A%C3%B1os.jpg"],
    description: "Top Cuello Alto & Jean Cargo 2 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-016",
    slug: "blusa-rayas-corazon--jean-3-anos",
    name: "Blusa Rayas Corazón & Jean 3 Años",
    category: "jeans",
    ageGroup: ["3"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 36,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["3"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Blusa%20Rayas%20Coraz%C3%B3n%20%26%20Jean%203%20A%C3%B1os.jpg"],
    description: "Blusa Rayas Corazón & Jean 3 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-017",
    slug: "polera-cherry--jean-pierna-ancha-4-anos",
    name: "Polera Cherry & Jean Pierna Ancha 4 Años",
    category: "jeans",
    ageGroup: ["4"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 37,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Polera%20Cherry%20%26%20Jean%20Pierna%20Ancha%204%20A%C3%B1os.jpg"],
    description: "Polera Cherry & Jean Pierna Ancha 4 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-018",
    slug: "blusa-floral--jean-vaqueros-5-anos",
    name: "Blusa Floral & Jean Vaqueros 5 Años",
    category: "jeans",
    ageGroup: ["5"],
    season: "todo-el-año",
    price: 45,
    oldPrice: 65,
    badge: "oferta",
    rating: 4.8,
    reviews: 38,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["5"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Blusa%20Floral%20%26%20Jean%20Vaqueros%205%20A%C3%B1os.jpg"],
    description: "Blusa Floral & Jean Vaqueros 5 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-019",
    slug: "blusa-floreada--jean-acampanado-6-anos",
    name: "Blusa Floreada & Jean Acampanado 6 Años",
    category: "jeans",
    ageGroup: ["6"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 39,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["6"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Blusa%20Floreada%20%26%20Jean%20Acampanado%206%20A%C3%B1os.jpg"],
    description: "Blusa Floreada & Jean Acampanado 6 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-020",
    slug: "jean-con-lazos-negros-coquette-7-anos",
    name: "Jean con Lazos Negros Coquette 7 Años",
    category: "jeans",
    ageGroup: ["7"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 40,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["7"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Jean%20con%20Lazos%20Negros%20Coquette%207%20A%C3%B1os.jpg"],
    description: "Jean con Lazos Negros Coquette 7 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-021",
    slug: "conjunto-3-pzs-chaqueta--chompa-conejo--pantalon-1",
    name: "Conjunto 3 PZS Chaqueta + Chompa Conejo + Pantalón 12-18M",
    category: "conjuntos",
    ageGroup: ["12-18M"],
    season: "invierno",
    price: 39,
    oldPrice: 59,
    badge: "oferta",
    rating: 4.8,
    reviews: 41,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12-18M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%203%20PZS%20Chaqueta%20%2B%20Chompa%20Conejo%20%2B%20Pantal%C3%B3n%2012-18M.jpg"],
    description: "Conjunto 3 PZS Chaqueta + Chompa Conejo + Pantalón 12-18M - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-022",
    slug: "conjunto-bebe-recien-nacido-3-piezas-felpa-con-laz",
    name: "Conjunto Bebé Recién Nacido 3 Piezas Felpa con Lazo 12M",
    category: "conjuntos",
    ageGroup: ["12M"],
    season: "invierno",
    price: 39,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 42,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%20Beb%C3%A9%20Reci%C3%A9n%20Nacido%203%20Piezas%20Felpa%20con%20Lazo%2012M.jpg"],
    description: "Conjunto Bebé Recién Nacido 3 Piezas Felpa con Lazo 12M - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-023",
    slug: "conjunto-3-piezas-gris-minnie-daisy-3-4-anos",
    name: "Conjunto 3 Piezas Gris Minnie Daisy 3-4 Años",
    category: "conjuntos",
    ageGroup: ["3-4"],
    season: "invierno",
    price: 39,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 43,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["3-4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%203%20Piezas%20Gris%20Minnie%20Daisy%203-4%20A%C3%B1os.jpg"],
    description: "Conjunto 3 Piezas Gris Minnie Daisy 3-4 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-024",
    slug: "conjunto-lila-perrito-3-4-anos",
    name: "Conjunto Lila Perrito 3-4 Años",
    category: "conjuntos",
    ageGroup: ["3-4"],
    season: "invierno",
    price: 39,
    oldPrice: 59,
    badge: "nuevo",
    rating: 4.8,
    reviews: 44,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["3-4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%20Lila%20Perrito%203-4%20A%C3%B1os.jpg"],
    description: "Conjunto Lila Perrito 3-4 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-025",
    slug: "conjunto-3-piezas-retro-mollie-mae-topchalecopanta",
    name: "Conjunto 3 Piezas Retro Mollie Mae Top+Chaleco+Pantalón 4-5A",
    category: "conjuntos",
    ageGroup: ["4-5"],
    season: "invierno",
    price: 39,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 45,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["4-5"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20Top%2BChaleco%2BPantal%C3%B3n%204-5A.jpg"],
    description: "Conjunto 3 Piezas Retro Mollie Mae Top+Chaleco+Pantalón 4-5A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-026",
    slug: "conjunto-love-fucsia-2-piezas-5-6-anos",
    name: "Conjunto Love Fucsia 2 Piezas 5-6 Años",
    category: "conjuntos",
    ageGroup: ["5-6"],
    season: "invierno",
    price: 39,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 46,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["5-6"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%20Love%20Fucsia%202%20Piezas%205-6%20A%C3%B1os.jpg"],
    description: "Conjunto Love Fucsia 2 Piezas 5-6 Años - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-027",
    slug: "conjunto-2-pzs-invierno-abrigo--pantalon-termico-6",
    name: "Conjunto 2 PZS Invierno Abrigo + Pantalón Térmico 6-7A",
    category: "conjuntos",
    ageGroup: ["6-7"],
    season: "invierno",
    price: 39,
    oldPrice: 59,
    badge: "oferta",
    rating: 4.8,
    reviews: 47,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["6-7"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%202%20PZS%20Invierno%20Abrigo%20%2B%20Pantal%C3%B3n%20T%C3%A9rmico%206-7A.jpg"],
    description: "Conjunto 2 PZS Invierno Abrigo + Pantalón Térmico 6-7A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-028",
    slug: "chompa-monstruos",
    name: "Chompa Monstruos",
    category: "casacas",
    ageGroup: ["12M"],
    season: "invierno",
    price: 45,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 48,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Chompa%20Monstruos.jpg"],
    description: "Chompa Monstruos - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-029",
    slug: "chompa-rayas-cafe",
    name: "Chompa Rayas Café",
    category: "casacas",
    ageGroup: ["12M"],
    season: "invierno",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 49,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Chompa%20Rayas%20Caf%C3%A9.jpg"],
    description: "Chompa Rayas Café - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-030",
    slug: "chompa-dinosaurios",
    name: "Chompa Dinosaurios",
    category: "casacas",
    ageGroup: ["12M"],
    season: "invierno",
    price: 45,
    oldPrice: 65,
    badge: "oferta",
    rating: 4.8,
    reviews: 50,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Chompa%20Dinosaurios.jpg"],
    description: "Chompa Dinosaurios - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-031",
    slug: "cardigan-fresa-rosa",
    name: "Cárdigan Fresa Rosa",
    category: "casacas",
    ageGroup: ["12M"],
    season: "invierno",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 51,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/C%C3%A1rdigan%20Fresa%20Rosa.jpg"],
    description: "Cárdigan Fresa Rosa - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-032",
    slug: "cardigan-corazones-cuadros-2a",
    name: "Cárdigan Corazones Cuadros 2A",
    category: "casacas",
    ageGroup: ["2"],
    season: "invierno",
    price: 45,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 52,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/C%C3%A1rdigan%20Corazones%20Cuadros%202A.jpg"],
    description: "Cárdigan Corazones Cuadros 2A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-033",
    slug: "cardigan-fresa-rosa-3a",
    name: "Cárdigan Fresa Rosa 3A",
    category: "casacas",
    ageGroup: ["3"],
    season: "invierno",
    price: 45,
    oldPrice: 65,
    badge: "oferta",
    rating: 4.8,
    reviews: 53,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["3"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/C%C3%A1rdigan%20Fresa%20Rosa%203A.jpg"],
    description: "Cárdigan Fresa Rosa 3A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-034",
    slug: "cardigan-dinosaurios-coloridos-4a",
    name: "Cárdigan Dinosaurios Coloridos 4A",
    category: "casacas",
    ageGroup: ["4"],
    season: "invierno",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 54,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/C%C3%A1rdigan%20Dinosaurios%20Coloridos%204A.jpg"],
    description: "Cárdigan Dinosaurios Coloridos 4A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-035",
    slug: "cardigan-fresas-y-corazones-rosado-5a",
    name: "Cárdigan Fresas y Corazones Rosado 5A",
    category: "casacas",
    ageGroup: ["5"],
    season: "invierno",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 55,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["5"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/C%C3%A1rdigan%20Fresas%20y%20Corazones%20Rosado%205A.jpg"],
    description: "Cárdigan Fresas y Corazones Rosado 5A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-036",
    slug: "cardigan-estampado-monstruos-6a",
    name: "Cárdigan Estampado Monstruos 6A",
    category: "casacas",
    ageGroup: ["6"],
    season: "invierno",
    price: 45,
    oldPrice: 65,
    badge: "nuevo",
    rating: 4.8,
    reviews: 56,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["6"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/C%C3%A1rdigan%20Estampado%20Monstruos%206A.jpg"],
    description: "Cárdigan Estampado Monstruos 6A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-037",
    slug: "casaca-corazon-2-4a",
    name: "Casaca Corazón 2-4A",
    category: "casacas",
    ageGroup: ["2-4"],
    season: "invierno",
    price: 49,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 57,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2-4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Casaca%20Coraz%C3%B3n%202-4A.jpg"],
    description: "Casaca Corazón 2-4A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-038",
    slug: "casaca-conejo-2-4a",
    name: "Casaca Conejo 2-4A",
    category: "casacas",
    ageGroup: ["2-4"],
    season: "invierno",
    price: 49,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 58,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2-4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Casaca%20Conejo%202-4A.jpg"],
    description: "Casaca Conejo 2-4A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-039",
    slug: "casaca-mariposa-3d-2-4a",
    name: "Casaca Mariposa 3D 2-4A",
    category: "casacas",
    ageGroup: ["2-4"],
    season: "invierno",
    price: 49,
    oldPrice: 69,
    badge: "oferta",
    rating: 4.8,
    reviews: 59,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2-4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Casaca%20Mariposa%203D%202-4A.jpg"],
    description: "Casaca Mariposa 3D 2-4A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-040",
    slug: "casaca-mariposa-bombom-2-4a",
    name: "Casaca Mariposa Bombom 2-4A",
    category: "casacas",
    ageGroup: ["2-4"],
    season: "invierno",
    price: 49,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 60,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2-4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Casaca%20Mariposa%20Bombom%202-4A.jpg"],
    description: "Casaca Mariposa Bombom 2-4A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-041",
    slug: "casaca-gopennig-amarillo-nino",
    name: "Casaca GOPENNIG Amarillo Niño",
    category: "casacas",
    ageGroup: ["2-4"],
    season: "invierno",
    price: 49,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 61,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2-4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Casaca%20GOPENNIG%20Amarillo%20Ni%C3%B1o.jpg"],
    description: "Casaca GOPENNIG Amarillo Niño - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-042",
    slug: "conjunto-2-pzs-calvin-hoodie-letras--pantalon-12m",
    name: "Conjunto 2 PZS Calvin Hoodie Letras + Pantalón 12M",
    category: "conjuntos",
    ageGroup: ["12M"],
    season: "invierno",
    price: 39,
    oldPrice: 59,
    badge: "oferta",
    rating: 4.8,
    reviews: 62,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%202%20PZS%20Calvin%20Hoodie%20Letras%20%2B%20Pantal%C3%B3n%2012M.jpg"],
    description: "Conjunto 2 PZS Calvin Hoodie Letras + Pantalón 12M - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-043",
    slug: "conjunto-3-pzs-leon-simba-felpa-piel-de-oso-12-18m",
    name: "Conjunto 3 PZS León Simba Felpa Piel de Oso 12-18M",
    category: "conjuntos",
    ageGroup: ["12-18M"],
    season: "invierno",
    price: 39,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 63,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12-18M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%203%20PZS%20Le%C3%B3n%20Simba%20Felpa%20Piel%20de%20Oso%2012-18M.jpg"],
    description: "Conjunto 3 PZS León Simba Felpa Piel de Oso 12-18M - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-044",
    slug: "conjunto-urbano-nino-2-piezas-2-3a",
    name: "Conjunto Urbano Niño 2 Piezas 2-3A",
    category: "conjuntos",
    ageGroup: ["2-3"],
    season: "invierno",
    price: 39,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 64,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2-3"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%20Urbano%20Ni%C3%B1o%202%20Piezas%202-3A.jpg"],
    description: "Conjunto Urbano Niño 2 Piezas 2-3A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-045",
    slug: "conjunto-3-pzs-dinosaurio-chalecopolerapantalon-4-",
    name: "Conjunto 3 Pzs Dinosaurio Chaleco+Polera+Pantalón 4-5A",
    category: "conjuntos",
    ageGroup: ["4-5"],
    season: "invierno",
    price: 39,
    oldPrice: 59,
    badge: "oferta",
    rating: 4.8,
    reviews: 65,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["4-5"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%203%20Pzs%20Dinosaurio%20Chaleco%2BPolera%2BPantal%C3%B3n%204-5A.jpg"],
    description: "Conjunto 3 Pzs Dinosaurio Chaleco+Polera+Pantalón 4-5A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-046",
    slug: "conjunto-osito-otonal-nino-gduck-5-6a",
    name: "Conjunto Osito Otoñal Niño GDUCK 5-6A",
    category: "conjuntos",
    ageGroup: ["5-6"],
    season: "invierno",
    price: 39,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 66,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["5-6"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Conjunto%20Osito%20Oto%C3%B1al%20Ni%C3%B1o%20GDUCK%205-6A.jpg"],
    description: "Conjunto Osito Otoñal Niño GDUCK 5-6A - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-047",
    slug: "sudadera-so-what-negro--jeans-rasgado-12-18m-nino",
    name: "Sudadera So What Negro & Jeans Rasgado 12-18M Niño",
    category: "jeans",
    ageGroup: ["12-18M"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 67,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["12-18M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Sudadera%20So%20What%20Negro%20%26%20Jeans%20Rasgado%2012-18M%20Ni%C3%B1o.jpg"],
    description: "Sudadera So What Negro & Jeans Rasgado 12-18M Niño - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-048",
    slug: "overol-jean-azul--polo-manga-larga-white-18-24m-ni",
    name: "Overol jean azul & Polo manga larga white 18-24M Niño",
    category: "jeans",
    ageGroup: ["18-24M"],
    season: "todo-el-año",
    price: 45,
    oldPrice: 65,
    badge: "nuevo",
    rating: 4.8,
    reviews: 68,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["18-24M"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Overol%20jean%20azul%20%26%20Polo%20manga%20larga%20white%2018-24M%20Ni%C3%B1o.jpg"],
    description: "Overol jean azul & Polo manga larga white 18-24M Niño - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-049",
    slug: "polo-waffle-rayas-beigenegro--jeans-2-3a-nino",
    name: "Polo waffle rayas beige/negro & Jeans 2-3A Niño",
    category: "jeans",
    ageGroup: ["2-3"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 69,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["2-3"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Polo%20waffle%20rayas%20beige/negro%20%26%20Jeans%202-3A%20Ni%C3%B1o.jpg"],
    description: "Polo waffle rayas beige/negro & Jeans 2-3A Niño - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  },
  {
    id: "mk-050",
    slug: "sudadera-beige-parche-cb--jean-rasgado-be-happy-3-",
    name: "Sudadera beige parche CB & Jean rasgado BE HAPPY 3-4A Niño",
    category: "jeans",
    ageGroup: ["3-4"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "",
    rating: 4.8,
    reviews: 70,
    stock: 10,
    colors: [{ name: "Mixto", hex: "#F3B9C6" }],
    sizes: ["3-4"],
    images: ["https://navemed.github.io/catalogo-marie-kids/img/Invierno/COD%20120%204A%C3%91OS/NI%C3%91A/TALLA%205%20Conjunto%203%20Piezas%20Retro%20Mollie%20Mae%20(Top%20+%20Chaleco%20+%20Pantal%C3%B3n.jpg)", "https://navemed.github.io/catalogo-marie-kids/img/Invierno/Sudadera%20beige%20parche%20CB%20%26%20Jean%20rasgado%20BE%20HAPPY%203-4A%20Ni%C3%B1o.jpg"],
    description: "Sudadera beige parche CB & Jean rasgado BE HAPPY 3-4A Niño - Producto original Marie Kids importado, calidad premium.",
    material: "Algodón / Denim / Felpa importada",
    care: "Lavado a mano en frío."
  }
];

const CATEGORIES = [
  { slug: "vestidos", name: "Vestidos", emoji: "👗" },
  { slug: "conjuntos", name: "Conjuntos", emoji: "🎀" },
  { slug: "casacas", name: "Casacas", emoji: "🧥" },
  { slug: "jeans", name: "Jeans", emoji: "👖" },
  { slug: "invierno", name: "Invierno", emoji: "❄️" },
  { slug: "nino", name: "Niño", emoji: "👦" },
  { slug: "nuevos", name: "Nuevos ingresos", emoji: "✨" },
  { slug: "liquidacion", name: "Liquidación", emoji: "🏷️" },
];

function resolvePlaceholder(str) {
  if (str.startsWith("http")) return { grad: "real", emoji: "🖼️", url: str };
  const [, grad, emoji] = str.split(":");
  return { grad, emoji };
}
