/* ============================================================
   DATA.JS — Catálogo de productos de ejemplo
   ------------------------------------------------------------
   Esto simula lo que en producción vendría de una base de datos
   (Supabase / PostgreSQL). Cada producto tiene la misma forma
   que tendría una fila de la tabla `products`, para que el día
   que conectes Supabase, solo tengas que reemplazar esta lista
   estática por un fetch() real — el resto del código (render,
   carrito, filtros, búsqueda) no necesita cambiar.

   Ver /README.md → sección "Esquema de base de datos sugerido"
   ============================================================ */

const PRODUCTS = [
  {
    id: "vf-001",
    slug: "vestido-fiesta-bautizo-crema-tul",
    name: "Vestido Fiesta Bautizo Crema Tul",
    category: "vestidos",
    ageGroup: ["12-18M", "2-3"],
    season: "verano",
    price: 49,
    oldPrice: 69,
    badge: "oferta",
    rating: 4.8,
    reviews: 34,
    stock: 12,
    colors: [{ name: "Crema", hex: "#F3E9DC" }, { name: "Blanco", hex: "#FFFFFF" }],
    sizes: ["12-18M", "2-3", "4"],
    images: ["placeholder:g1:👗", "placeholder:g1b:🎀"],
    description: "Vestido de fiesta en tul crema con bordado floral, ideal para bautizos y ceremonias especiales. Forro interior suave, cierre posterior con cremallera.",
    material: "Tul importado 100% poliéster, forro de algodón.",
    care: "Lavado a mano, no usar secadora, planchar a baja temperatura.",
  },
  {
    id: "cd-002",
    slug: "conjunto-denim-nina-osito",
    name: "Conjunto Denim Niña Osito",
    category: "conjuntos",
    ageGroup: ["5-6", "6"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.9,
    reviews: 21,
    stock: 8,
    colors: [{ name: "Celeste", hex: "#AEE3F0" }],
    sizes: ["4", "5-6", "6"],
    images: ["placeholder:g2:👕", "placeholder:g2b:🧸"],
    description: "Conjunto de dos piezas en denim suave con estampado de osito. Cintura elástica para mayor comodidad.",
    material: "Denim 98% algodón, 2% elastano.",
    care: "Lavado a máquina en frío, del revés.",
  },
  {
    id: "cm-003",
    slug: "casaca-mariposa-3d-abrigadora",
    name: "Casaca Mariposa 3D Abrigadora",
    category: "casacas",
    ageGroup: ["3", "4", "5-6"],
    season: "invierno",
    price: 59,
    oldPrice: 79,
    badge: "oferta",
    rating: 4.7,
    reviews: 45,
    stock: 5,
    colors: [{ name: "Beige", hex: "#EDDFCB" }, { name: "Rosa", hex: "#F3B9C6" }],
    sizes: ["3", "4", "5-6"],
    images: ["placeholder:g3:🧥", "placeholder:g3b:🦋"],
    description: "Casaca abrigadora con aplique de mariposa 3D y capucha desmontable con forro polar interior.",
    material: "Exterior impermeable, relleno acolchado, forro polar.",
    care: "Lavado a mano, secar en horizontal.",
  },
  {
    id: "co-004",
    slug: "conjunto-chaqueta-chompa-oso",
    name: "Conjunto Chaqueta + Chompa Oso",
    category: "invierno",
    ageGroup: ["12M", "2-3"],
    season: "invierno",
    price: 39,
    oldPrice: null,
    badge: "nuevo",
    rating: 5.0,
    reviews: 12,
    stock: 15,
    colors: [{ name: "Marrón", hex: "#B98D63" }],
    sizes: ["12M", "2-3"],
    images: ["placeholder:g4:🐻", "placeholder:g4b:🧶"],
    description: "Conjunto de 3 piezas: chaqueta, chompa y pantalón a juego con estampado de osito. Perfecto para el frío.",
    material: "Franela afelpada, muy suave al tacto.",
    care: "Lavado a máquina en frío.",
  },
  {
    id: "vp-005",
    slug: "vestido-princesa-bebe-gala",
    name: "Vestido Princesa Bebé Gala",
    category: "vestidos",
    ageGroup: ["12-18M", "2"],
    season: "verano",
    price: 49,
    oldPrice: 65,
    badge: "oferta",
    rating: 4.9,
    reviews: 58,
    stock: 3,
    colors: [{ name: "Rosa", hex: "#F8C8DC" }, { name: "Lila", hex: "#C8B6FF" }],
    sizes: ["12-18M", "2"],
    images: ["placeholder:g5:👑", "placeholder:g5b:✨"],
    description: "Vestido de gala con falda de tul en capas y diadema a juego incluida. Ideal para sesiones de fotos y cumpleaños.",
    material: "Tul y satén, forro de algodón.",
    care: "Lavado a mano exclusivamente.",
  },
  {
    id: "cj-006",
    slug: "conjunto-jean-polo-rayas",
    name: "Conjunto Jean + Polo Rayas",
    category: "jeans",
    ageGroup: ["4", "5-6", "6"],
    season: "todo-el-año",
    price: 45,
    oldPrice: null,
    badge: null,
    rating: 4.6,
    reviews: 19,
    stock: 20,
    colors: [{ name: "Azul", hex: "#5B7FA6" }],
    sizes: ["4", "5-6", "6"],
    images: ["placeholder:g6:👖", "placeholder:g6b:🎽"],
    description: "Conjunto de jean recto con polo a rayas. Básico versátil para el día a día.",
    material: "Denim stretch, polo de algodón pima.",
    care: "Lavado a máquina en frío.",
  },
  {
    id: "cc-007",
    slug: "casaca-conejo-rosa-peluche",
    name: "Casaca Conejo Rosa Peluche",
    category: "casacas",
    ageGroup: ["2-3", "4"],
    season: "invierno",
    price: 55,
    oldPrice: null,
    badge: "nuevo",
    rating: 4.8,
    reviews: 27,
    stock: 9,
    colors: [{ name: "Rosa", hex: "#F3B9C6" }],
    sizes: ["2-3", "4"],
    images: ["placeholder:g7:🐰", "placeholder:g7b:🌸"],
    description: "Casaca tipo peluche con orejitas de conejo en la capucha. Súper abrigadora y adorable.",
    material: "Peluche sherpa, interior forrado.",
    care: "Lavado a mano, no retorcer.",
  },
  {
    id: "cf-008",
    slug: "conjunto-cardigan-fresa-3pzs",
    name: "Conjunto Cárdigan Fresa 3 Pzs",
    category: "conjuntos",
    ageGroup: ["3", "4", "5-6"],
    season: "otoño",
    price: 42,
    oldPrice: 58,
    badge: "más-vendido",
    rating: 4.9,
    reviews: 63,
    stock: 6,
    colors: [{ name: "Rojo", hex: "#D6488B" }, { name: "Blanco", hex: "#FFFFFF" }],
    sizes: ["3", "4", "5-6"],
    images: ["placeholder:g8:🍓", "placeholder:g8b:🌟"],
    description: "Set de 3 piezas: cárdigan, top y falda con estampado de fresas. Combinable de mil formas.",
    material: "Punto de algodón suave.",
    care: "Lavado a máquina en frío, del revés.",
  },
];

/* Categorías del menú / mega menú */
const CATEGORIES = [
  { slug: "vestidos", name: "Vestidos", emoji: "👗" },
  { slug: "conjuntos", name: "Conjuntos", emoji: "🎀" },
  { slug: "casacas", name: "Casacas", emoji: "🧥" },
  { slug: "jeans", name: "Jeans", emoji: "👖" },
  { slug: "invierno", name: "Invierno", emoji: "❄️" },
  { slug: "liquidacion", name: "Liquidación", emoji: "🏷️" },
  { slug: "nuevos", name: "Nuevos ingresos", emoji: "✨" },
  { slug: "cumpleanos", name: "Cumpleaños", emoji: "🎂" },
  { slug: "accesorios", name: "Accesorios", emoji: "🎁" },
];

/* Utilidad: emoji-placeholder -> se usa mientras no hay fotos reales.
   Formato: "placeholder:<gradiente>:<emoji>" */
function resolvePlaceholder(str) {
  const [, grad, emoji] = str.split(":");
  return { grad, emoji };
}
