const productos = [
  { name: "2 conjunto 2 pzs pantal n osito gris", cod: "90", talla: "18-24 Meses", category: "cardigans-nina", image: "/img/cardigans-nina/2-conjunto-2-pzs-pantal-n-osito-gris-90-18-24M.jpg", price: 55 },
  { name: "2 conjunto 3 pzs dino azul chaleco sudad", cod: "90", talla: "18-24 Meses", category: "cardigans-nina", image: "/img/cardigans-nina/2-conjunto-3-pzs-dino-azul-chaleco-sudad-90-18-24M.jpg", price: 55 },
  { name: "2 conjunto 3 pzs king polo capucha chale", cod: "90", talla: "18-24 Meses", category: "cardigans-nina", image: "/img/cardigans-nina/2-conjunto-3-pzs-king-polo-capucha-chale-90-18-24M.jpg", price: 55 },
  { name: "2 conjunto de 2 piezas para beb ni o peq", cod: "90", talla: "18-24 Meses", category: "cardigans-nina", image: "/img/cardigans-nina/2-conjunto-de-2-piezas-para-beb-ni-o-peq-90-18-24M.jpg", price: 55 },
  { name: "2 conjunto de overoles peludos y adorabl", cod: "90", talla: "18-24 Meses", category: "cardigans-nina", image: "/img/cardigans-nina/2-conjunto-de-overoles-peludos-y-adorabl-90-18-24M.jpg", price: 55 },
  { name: "2 conjunto ni a corazones c rdigan panta", cod: "90", talla: "18-24 Meses", category: "cardigans-nina", image: "/img/cardigans-nina/2-conjunto-ni-a-corazones-c-rdigan-panta-90-18-24M.jpg", price: 55 },
  { name: "2 conjunto osito 3 piezas con morralito", cod: "90", talla: "18-24 Meses", category: "cardigans-nina", image: "/img/cardigans-nina/2-conjunto-osito-3-piezas-con-morralito-90-18-24M.jpg", price: 55 },
  { name: "3 conjunto 2 piezas letras con capucha o", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-2-piezas-letras-con-capucha-o-100-2A.jpg", price: 55 },
  { name: "3 conjunto 2 piezas ni o chaqueta color", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-2-piezas-ni-o-chaqueta-color-100-2A.jpg", price: 55 },
  { name: "3 conjunto 2 pzs bolso beb marr n", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-2-pzs-bolso-beb-marr-n-100-2A.jpg", price: 55 },
  { name: "3 conjunto 2 pzs chaquetas ni a capucha", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-2-pzs-chaquetas-ni-a-capucha-100-2A.jpg", price: 55 },
  { name: "3 conjunto 2 pzs ni a polo corazones man", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-2-pzs-ni-a-polo-corazones-man-100-2A.jpg", price: 55 },
  { name: "3 conjunto 3 piezas gris minnie daisy ch", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-3-piezas-gris-minnie-daisy-ch-110-3A.jpg", price: 55 },
  { name: "3 conjunto 3 pzs mo ito coraz n chaleco", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-3-pzs-mo-ito-coraz-n-chaleco-110-3A.jpg", price: 55 },
  { name: "3 conjunto dino 2 piezas con capucha", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-dino-2-piezas-con-capucha-100-2A.jpg", price: 55 },
  { name: "3 conjunto lila perrito 3 4 chompa", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-lila-perrito-3-4-chompa-110-3A.jpg", price: 55 },
  { name: "3 conjunto navy blue mo itos 2 piezas", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-navy-blue-mo-itos-2-piezas-110-3A.jpg", price: 55 },
  { name: "3 conjunto osito 3 piezas con morralito", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-osito-3-piezas-con-morralito-100-2A.jpg", price: 55 },
  { name: "3 conjunto osito oto al ni o gduck", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-osito-oto-al-ni-o-gduck-100-2A.jpg", price: 55 },
  { name: "3 conjunto urbano ni o 2 piezas", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-conjunto-urbano-ni-o-2-piezas-100-2A.jpg", price: 55 },
  { name: "3 set abrigador beb 3 pzs", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/3-set-abrigador-beb-3-pzs-100-2A.jpg", price: 55 },
  { name: "4 conjunto 2 pzs chaquetas ni a capucha", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-2-pzs-chaquetas-ni-a-capucha-110-3A.jpg", price: 55 },
  { name: "4 conjunto 2 pzs invierno abrigo pantal", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-2-pzs-invierno-abrigo-pantal-110-3A.jpg", price: 55 },
  { name: "4 conjunto 2 pzs ni a sudadera capucha l", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-2-pzs-ni-a-sudadera-capucha-l-110-3A.jpg", price: 55 },
  { name: "4 conjunto 2 pzs ni a sudadera lazo mang", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-2-pzs-ni-a-sudadera-lazo-mang-110-3A.jpg", price: 55 },
  { name: "4 conjunto 2pzs ni a varsity girl casaca", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-2pzs-ni-a-varsity-girl-casaca-110-3A.jpg", price: 55 },
  { name: "4 conjunto 3 pzs beb polo chaleco oso pa", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-3-pzs-beb-polo-chaleco-oso-pa-110-3A.jpg", price: 55 },
  { name: "4 conjunto 3 pzs conejo unisex felpa gru", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-3-pzs-conejo-unisex-felpa-gru-110-3A.jpg", price: 55 },
  { name: "4 conjunto 3 pzs goat gris", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-3-pzs-goat-gris-110-3A.jpg", price: 55 },
  { name: "4 conjunto cuello alto con cremallera ni", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-cuello-alto-con-cremallera-ni-110-3A.jpg", price: 55 },
  { name: "4 conjunto de overoles peludos y adorabl", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-de-overoles-peludos-y-adorabl-110-3A.jpg", price: 55 },
  { name: "4 conjunto deportivo juvenil azul 2 piez", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-deportivo-juvenil-azul-2-piez-110-3A.jpg", price: 55 },
  { name: "4 conjunto felpito 2 piezas beb", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-felpito-2-piezas-beb-110-3A.jpg", price: 55 },
  { name: "4 conjunto polar forrado con capucha 2 p", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-polar-forrado-con-capucha-2-p-110-3A.jpg", price: 55 },
  { name: "4 conjunto set 3 pzs capucha y chaleco 2", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-set-3-pzs-capucha-y-chaleco-2-110-3A.jpg", price: 55 },
  { name: "4 conjunto urbano ni o 2 piezas", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-conjunto-urbano-ni-o-2-piezas-110-3A.jpg", price: 55 },
  { name: "4 set abrigador beb 3 pzs", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/4-set-abrigador-beb-3-pzs-110-3A.jpg", price: 55 },
  { name: "5 conjunto 2 pzs bolso ni o primavera", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-2-pzs-bolso-ni-o-primavera-120-4A.jpg", price: 55 },
  { name: "5 conjunto 2 pzs ni a top manga larga pa", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-2-pzs-ni-a-top-manga-larga-pa-120-4A.jpg", price: 55 },
  { name: "5 conjunto 3 piezas retro mollie mae top", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-3-piezas-retro-mollie-mae-top-120-4A.jpg", price: 55 },
  { name: "5 conjunto 3 pzs dinosaurio chaleco pole", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-3-pzs-dinosaurio-chaleco-pole-120-4A.jpg", price: 55 },
  { name: "5 conjunto beisbol dreams azul 2 pzs", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-beisbol-dreams-azul-2-pzs-120-4A.jpg", price: 55 },
  { name: "5 conjunto beisbol letra k 2 pzs", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-beisbol-letra-k-2-pzs-120-4A.jpg", price: 55 },
  { name: "5 conjunto buzo bloques estampado oto o", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-buzo-bloques-estampado-oto-o-120-4A.jpg", price: 55 },
  { name: "5 conjunto buzo verde letras 2 pzs oto o", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-buzo-verde-letras-2-pzs-oto-o-120-4A.jpg", price: 55 },
  { name: "5 conjunto love fucsia 2 piezas", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-love-fucsia-2-piezas-130-5A.jpg", price: 55 },
  { name: "5 conjunto marr n acolchado nope 2 pzs", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-marr-n-acolchado-nope-2-pzs-120-4A.jpg", price: 55 },
  { name: "5 conjunto ni a 2 piezas casual oto o in", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-ni-a-2-piezas-casual-oto-o-in-120-4A.jpg", price: 55 },
  { name: "5 conjunto ni a invierno flowers love 3", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-ni-a-invierno-flowers-love-3-120-4A.jpg", price: 55 },
  { name: "5 conjunto peluche rosa ni a 2 piezas ca", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-peluche-rosa-ni-a-2-piezas-ca-120-4A.jpg", price: 55 },
  { name: "5 conjunto urbano polar casaca pantal n", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-conjunto-urbano-polar-casaca-pantal-n-120-4A.jpg", price: 55 },
  { name: "5 pijama ni a invierno 2 piezas conejito", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/5-pijama-ni-a-invierno-2-piezas-conejito-120-4A.jpg", price: 55 },
  { name: "6 conjunto 2 pzs conejo chaqueta capucha", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-2-pzs-conejo-chaqueta-capucha-130-5A.jpg", price: 55 },
  { name: "6 conjunto 2 pzs invierno abrigo pantal", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-2-pzs-invierno-abrigo-pantal-140-6A-01.jpg", price: 55 },
  { name: "6 conjunto 2 pzs invierno abrigo pantal", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-2-pzs-invierno-abrigo-pantal-140-6A.jpg", price: 55 },
  { name: "6 conjunto 2pzs ni a elegante lazo casac", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-2pzs-ni-a-elegante-lazo-casac-140-6A-01.jpg", price: 55 },
  { name: "6 conjunto 2pzs ni a elegante lazo casac", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-2pzs-ni-a-elegante-lazo-casac-140-6A.jpg", price: 55 },
  { name: "6 conjunto beige tri ngulo forro peluche", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-beige-tri-ngulo-forro-peluche-130-5A.jpg", price: 55 },
  { name: "6 conjunto donabebe invierno 2 pzs", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-donabebe-invierno-2-pzs-130-5A.jpg", price: 55 },
  { name: "6 conjunto gris nope 2 pzs forrado", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-gris-nope-2-pzs-forrado-130-5A.jpg", price: 55 },
  { name: "6 conjunto ni a 2 piezas polar liso casa", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-ni-a-2-piezas-polar-liso-casa-130-5A.jpg", price: 55 },
  { name: "6 conjunto osito oto al ni o gduck", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-osito-oto-al-ni-o-gduck-130-5A.jpg", price: 55 },
  { name: "6 conjunto urbano ni o 2 piezas", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-conjunto-urbano-ni-o-2-piezas-130-5A.jpg", price: 55 },
  { name: "6 set 2 pzs beige brave adolescente", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/6-set-2-pzs-beige-brave-adolescente-130-5A.jpg", price: 55 },
  { name: "c rdigan diamantes y conejitos", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/c-rdigan-diamantes-y-conejitos-110-3A.jpg", price: 55 },
  { name: "c rdigan punto estampado de fresas", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/c-rdigan-punto-estampado-de-fresas-120-4A.jpg", price: 55 },
  { name: "c rdigan punto estampado de fresas", cod: "150", talla: "7 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/c-rdigan-punto-estampado-de-fresas-150-7A.jpg", price: 55 },
  { name: "c rdigan punto estampado de fresas con c", cod: "150", talla: "7 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/c-rdigan-punto-estampado-de-fresas-con-c-150-7A.jpg", price: 55 },
  { name: "c rdigan rosa con corazones", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/c-rdigan-rosa-con-corazones-140-6A.jpg", price: 55 },
  { name: "cardigan corazones acuarela", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-corazones-acuarela-100-2A.jpg", price: 55 },
  { name: "cardigan corazones cuadros", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-corazones-cuadros-100-2A.jpg", price: 55 },
  { name: "cardigan diamantes conejitos", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-diamantes-conejitos-100-2A.jpg", price: 55 },
  { name: "cardigan diamantes conejitos", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-diamantes-conejitos-140-6A.jpg", price: 55 },
  { name: "cardigan flamencos", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-flamencos-100-2A.jpg", price: 55 },
  { name: "cardigan fresa", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-fresa-110-3A.jpg", price: 55 },
  { name: "cardigan fresa", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-fresa-140-6A.jpg", price: 55 },
  { name: "cardigan fresa", cod: "90", talla: "18-24 Meses", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-fresa-90-18-24M.jpg", price: 55 },
  { name: "cardigan fresas y corazones en tonos ros", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-fresas-y-corazones-en-tonos-ros-130-5A.jpg", price: 55 },
  { name: "cardigan monos rayas", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/cardigan-monos-rayas-100-2A.jpg", price: 55 },
  { name: "chompa colecci n rojo", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/chompa-colecci-n-rojo-140-6A.jpg", price: 55 },
  { name: "chompa de punto jacquard floral", cod: "120", talla: "4 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/chompa-de-punto-jacquard-floral-120-4A.jpg", price: 55 },
  { name: "chompa flores margaritas", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/chompa-flores-margaritas-100-2A.jpg", price: 55 },
  { name: "conejo", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/conejo-100-2A.jpg", price: 55 },
  { name: "corazon", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/corazon-100-2A.jpg", price: 55 },
  { name: "correa", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/correa-100-2A.jpg", price: 55 },
  { name: "estampado con figuras de vacas", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/estampado-con-figuras-de-vacas-130-5A.jpg", price: 55 },
  { name: "estampado de corazones", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/estampado-de-corazones-130-5A.jpg", price: 55 },
  { name: "estampado de corazones marrones", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/estampado-de-corazones-marrones-130-5A.jpg", price: 55 },
  { name: "estampado de fresas y flores", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/estampado-de-fresas-y-flores-140-6A.jpg", price: 55 },
  { name: "estampado de tulipanes en tonos naranja", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/estampado-de-tulipanes-en-tonos-naranja-130-5A.jpg", price: 55 },
  { name: "estampado leopardo", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/estampado-leopardo-130-5A.jpg", price: 55 },
  { name: "gopenni amarillo", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/gopenni-amarillo-100-2A.jpg", price: 55 },
  { name: "gopenni marron", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/gopenni-marron-100-2A.jpg", price: 55 },
  { name: "gopenni verde", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/gopenni-verde-100-2A.jpg", price: 55 },
  { name: "hong", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/hong-100-2A.jpg", price: 55 },
  { name: "mariposa 3d", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/mariposa-3d-100-2A.jpg", price: 55 },
  { name: "mariposa bombom", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/mariposa-bombom-100-2A.jpg", price: 55 },
  { name: "nuevo floral", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/nuevo-floral-110-3A.jpg", price: 55 },
  { name: "osito azul", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/osito-azul-110-3A.jpg", price: 55 },
  { name: "ositos y fresas de dibujos animados", cod: "140", talla: "6 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/ositos-y-fresas-de-dibujos-animados-140-6A.jpg", price: 55 },
  { name: "rosa con estampado de corazones", cod: "110", talla: "3 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/rosa-con-estampado-de-corazones-110-3A.jpg", price: 55 },
  { name: "sweater corazones crema", cod: "100", talla: "2 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/sweater-corazones-crema-100-2A.jpg", price: 55 },
  { name: "tejida con detalles de fresas", cod: "130", talla: "5 AÑOS", category: "cardigans-nina", image: "/img/cardigans-nina/tejida-con-detalles-de-fresas-130-5A.jpg", price: 55 },
  { name: "aventuras sobre ruedas", cod: "110", talla: "3 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/aventuras-sobre-ruedas-110-3A.jpg", price: 55 },
  { name: "azul rayas beige", cod: "120", talla: "4 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/azul-rayas-beige-120-4A.jpg", price: 55 },
  { name: "cardigan estampado de camellos 01", cod: "120", talla: "4 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/cardigan-estampado-de-camellos-01-120-4A.jpg", price: 55 },
  { name: "chompa de ositos beige", cod: "140", talla: "6 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/chompa-de-ositos-beige-140-6A.jpg", price: 55 },
  { name: "chompa dino", cod: "90", talla: "18-24 Meses", category: "cardigans-nino", image: "/img/cardigans-nino/chompa-dino-90-18-24M.jpg", price: 55 },
  { name: "chompa dino pastel", cod: "100", talla: "2 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/chompa-dino-pastel-100-2A.jpg", price: 55 },
  { name: "chompa dino pastel", cod: "140", talla: "6 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/chompa-dino-pastel-140-6A.jpg", price: 55 },
  { name: "chompa monstruos", cod: "140", talla: "6 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/chompa-monstruos-140-6A.jpg", price: 55 },
  { name: "chompa monstruos", cod: "90", talla: "18-24 Meses", category: "cardigans-nino", image: "/img/cardigans-nino/chompa-monstruos-90-18-24M.jpg", price: 55 },
  { name: "chompa rayas", cod: "90", talla: "18-24 Meses", category: "cardigans-nino", image: "/img/cardigans-nino/chompa-rayas-90-18-24M.jpg", price: 55 },
  { name: "chompa zigzag", cod: "110", talla: "3 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/chompa-zigzag-110-3A.jpg", price: 55 },
  { name: "chompitos amarillo", cod: "100", talla: "2 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/chompitos-amarillo-100-2A.jpg", price: 55 },
  { name: "estampado camellos 02", cod: "120", talla: "4 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/estampado-camellos-02-120-4A.jpg", price: 55 },
  { name: "estampado de dinosaurios coloridos", cod: "120", talla: "4 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/estampado-de-dinosaurios-coloridos-120-4A.jpg", price: 55 },
  { name: "franjas horizontales tonos de azul y cre", cod: "130", talla: "5 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/franjas-horizontales-tonos-de-azul-y-cre-130-5A.jpg", price: 55 },
  { name: "franjas horizontales tonos de azul y cre", cod: "140", talla: "6 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/franjas-horizontales-tonos-de-azul-y-cre-140-6A.jpg", price: 55 },
  { name: "granja encantada", cod: "110", talla: "3 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/granja-encantada-110-3A.jpg", price: 55 },
  { name: "osito love blanca", cod: "110", talla: "3 AÑOS", category: "cardigans-nino", image: "/img/cardigans-nino/osito-love-blanca-110-3A.jpg", price: 55 },
  { name: "12m conjunto 2 pzs calvin hoodie letras", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-2-pzs-calvin-hoodie-letras-90-18-24M.jpg", price: 55 },
  { name: "12m conjunto 2 pzs ni o ch ndal deportiv", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-2-pzs-ni-o-ch-ndal-deportiv-90-18-24M.jpg", price: 55 },
  { name: "12m conjunto 2 pzs ni o sudadera capucha", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-2-pzs-ni-o-sudadera-capucha-90-18-24M.jpg", price: 55 },
  { name: "12m conjunto 3 piezas para beb ni o colo", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-3-piezas-para-beb-ni-o-colo-90-18-24M.jpg", price: 55 },
  { name: "12m conjunto 3 pzs beb piel de oso negra", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-3-pzs-beb-piel-de-oso-negra-90-18-24M.jpg", price: 55 },
  { name: "12m conjunto 3 pzs beb sudadera letras c", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-3-pzs-beb-sudadera-letras-c-90-18-24M.jpg", price: 55 },
  { name: "12m conjunto 3 pzs le n simba gris plomo", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-3-pzs-le-n-simba-gris-plomo-90-18-24M.jpg", price: 55 },
  { name: "12m conjunto 3 pzs ni a chaqueta chompa", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-3-pzs-ni-a-chaqueta-chompa-90-18-24M.jpg", price: 55 },
  { name: "12m conjunto beb reci n nacido 3 piezas", cod: "90", talla: "18-24 Meses", category: "conjuntos-bebe", image: "/img/conjuntos-bebe/12m-conjunto-beb-reci-n-nacido-3-piezas-90-18-24M.jpg", price: 55 },
  { name: "camisa de manga larga con cuello vuelto", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/camisa-de-manga-larga-con-cuello-vuelto-90-18-24M.jpg", price: 55 },
  { name: "camiseta polo de manga larga de punto a", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/camiseta-polo-de-manga-larga-de-punto-a-100-2A.jpg", price: 55 },
  { name: "casaca vaquera vintage y pantalones depo", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/casaca-vaquera-vintage-y-pantalones-depo-90-18-24M.jpg", price: 55 },
  { name: "cod", cod: "140", talla: "6 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-130-kids-fashion-flat-lay-140-6A.jpg", price: 55 },
  { name: "cod", cod: "150", talla: "7 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-150-jean-archive-23-2-pzs-150-7A.jpg", price: 55 },
  { name: "cod 20 conjunto coquette ultra tendencia", cod: "140", talla: "6 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-20-conjunto-coquette-ultra-tendencia-140-6A.jpg", price: 55 },
  { name: "cod 200 blusa mangalarga cereza pack", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-200-blusa-mangalarga-cereza-pack-130-5A.jpg", price: 55 },
  { name: "cod 201 blusa floral y jean vaqueros pac", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-201-blusa-floral-y-jean-vaqueros-pac-130-5A.jpg", price: 55 },
  { name: "cod 201 blusa floreada y jean acampanado", cod: "140", talla: "6 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-201-blusa-floreada-y-jean-acampanado-140-6A.jpg", price: 55 },
  { name: "cod 2017 polo manga corta heart pantalon", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-2017-polo-manga-corta-heart-pantalon-100-2A.jpg", price: 55 },
  { name: "cod 2018 polera manga larga jeans azul c", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-2018-polera-manga-larga-jeans-azul-c-100-2A.jpg", price: 55 },
  { name: "cod 2019 camiseta de manga larga de cuel", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-2019-camiseta-de-manga-larga-de-cuel-100-2A.jpg", price: 55 },
  { name: "cod 202 blusa manga larga yelow pack", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-202-blusa-manga-larga-yelow-pack-120-4A.jpg", price: 55 },
  { name: "cod 202 blusa manga larga yelow pack", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-202-blusa-manga-larga-yelow-pack-130-5A.jpg", price: 55 },
  { name: "cod 2020 blusa manga larga yelow lazos p", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-2020-blusa-manga-larga-yelow-lazos-p-100-2A.jpg", price: 55 },
  { name: "cod 203 blusa manga corta yelow y jeans", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-203-blusa-manga-corta-yelow-y-jeans-130-5A.jpg", price: 55 },
  { name: "cod 204 manga corta y pantalones vaquero", cod: "140", talla: "6 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-204-manga-corta-y-pantalones-vaquero-140-6A.jpg", price: 55 },
  { name: "cod 205 blusita roja y jean acampanado", cod: "140", talla: "6 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-205-blusita-roja-y-jean-acampanado-140-6A.jpg", price: 55 },
  { name: "cod 206 polo mo o de lentejuelas y jean", cod: "150", talla: "7 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-206-polo-mo-o-de-lentejuelas-y-jean-150-7A.jpg", price: 55 },
  { name: "cod 207 blusa blanco de manga larga y ov", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-207-blusa-blanco-de-manga-larga-y-ov-130-5A.jpg", price: 55 },
  { name: "cod 208 blusa blanca manga larga y vaque", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-208-blusa-blanca-manga-larga-y-vaque-130-5A.jpg", price: 55 },
  { name: "cod 209 blusa blanca manga larga y panta", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-209-blusa-blanca-manga-larga-y-panta-130-5A.jpg", price: 55 },
  { name: "cod 209 blusa manga larga corta traje me", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-209-blusa-manga-larga-corta-traje-me-120-4A.jpg", price: 55 },
  { name: "cod 210 blusa manga corta rosa y pantalo", cod: "140", talla: "6 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-210-blusa-manga-corta-rosa-y-pantalo-140-6A.jpg", price: 55 },
  { name: "cod 211 chompa roja y jeans azul pack", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-211-chompa-roja-y-jeans-azul-pack-130-5A.jpg", price: 55 },
  { name: "cod 212 jeans cerezas pack", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-212-jeans-cerezas-pack-130-5A.jpg", price: 55 },
  { name: "cod 213 polera manga larga y pantalon pi", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-213-polera-manga-larga-y-pantalon-pi-120-4A.jpg", price: 55 },
  { name: "cod 214 blusa manga larga y pantalon pie", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-214-blusa-manga-larga-y-pantalon-pie-120-4A.jpg", price: 55 },
  { name: "cod 215 blusa con cuello de mu eca y man", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-215-blusa-con-cuello-de-mu-eca-y-man-120-4A.jpg", price: 55 },
  { name: "cod 215 overol largo azul oscuro con est", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-215-overol-largo-azul-oscuro-con-est-130-5A.jpg", price: 55 },
  { name: "cod 216 polo manga corta flores y jeans", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-216-polo-manga-corta-flores-y-jeans-120-4A.jpg", price: 55 },
  { name: "cod 221 blusa de manga larga de rayas co", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-221-blusa-de-manga-larga-de-rayas-co-110-3A.jpg", price: 55 },
  { name: "cod 222 pantalones vaqueros sudadera con", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-222-pantalones-vaqueros-sudadera-con-110-3A.jpg", price: 55 },
  { name: "cod 223 conjunto casual chaleco de cuell", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-223-conjunto-casual-chaleco-de-cuell-100-2A.jpg", price: 55 },
  { name: "cod 223 conjunto casual chaleco de cuell", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-223-conjunto-casual-chaleco-de-cuell-110-3A.jpg", price: 55 },
  { name: "cod 224 conjunto de top de puntilla con", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-224-conjunto-de-top-de-puntilla-con-100-2A.jpg", price: 55 },
  { name: "cod 224 polera manga larga lazo negro y", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-224-polera-manga-larga-lazo-negro-y-120-4A.jpg", price: 55 },
  { name: "cod 225 encaje floral manga larga y cuel", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-225-encaje-floral-manga-larga-y-cuel-130-5A.jpg", price: 55 },
  { name: "cod 226 set tr o cherry love con jean bo", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/cod-226-set-tr-o-cherry-love-con-jean-bo-90-18-24M.jpg", price: 55 },
  { name: "cod 227 set chompa blanca cereza y jean", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/cod-227-set-chompa-blanca-cereza-y-jean-90-18-24M.jpg", price: 55 },
  { name: "cod 228 chompa rosada bow y jean pack", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/cod-228-chompa-rosada-bow-y-jean-pack-90-18-24M.jpg", price: 55 },
  { name: "cod 229 conjunto denim cerezas pack", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/cod-229-conjunto-denim-cerezas-pack-90-18-24M.jpg", price: 55 },
  { name: "cod 230 chompa y jean con lazo pack", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/cod-230-chompa-y-jean-con-lazo-pack-90-18-24M.jpg", price: 55 },
  { name: "cod 231 overol de jean y polo manga larg", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/cod-231-overol-de-jean-y-polo-manga-larg-90-18-24M.jpg", price: 55 },
  { name: "cod 239 pantal n jean ni o papas fritas", cod: "150", talla: "7 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/cod-239-pantal-n-jean-ni-o-papas-fritas-150-7A.jpg", price: 55 },
  { name: "cod 240 denim jeans polo blanco", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/cod-240-denim-jeans-polo-blanco-90-18-24M.jpg", price: 55 },
  { name: "cod 241 denim jeans polo blanco", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/cod-241-denim-jeans-polo-blanco-90-18-24M.jpg", price: 55 },
  { name: "conjunto beb 2pz polera mommy s lucky bo", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-beb-2pz-polera-mommy-s-lucky-bo-110-3A.jpg", price: 55 },
  { name: "conjunto beb ni o 2pz polo manga corta j", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-beb-ni-o-2pz-polo-manga-corta-j-110-3A.jpg", price: 55 },
  { name: "conjunto beb ni o 2pz polo manga corta j", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-beb-ni-o-2pz-polo-manga-corta-j-120-4A.jpg", price: 55 },
  { name: "conjunto beb ni o jeans negros 2 piezas", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-beb-ni-o-jeans-negros-2-piezas-130-5A.jpg", price: 55 },
  { name: "conjunto beb osito blanco 2 piezas poler", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-beb-osito-blanco-2-piezas-poler-110-3A.jpg", price: 55 },
  { name: "conjunto de camisa y pantal n de patchwo", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-de-camisa-y-pantal-n-de-patchwo-110-3A.jpg", price: 55 },
  { name: "conjunto jeans ni o camisa cuadros bolsi", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-jeans-ni-o-camisa-cuadros-bolsi-110-3A.jpg", price: 55 },
  { name: "conjunto jeans ni o camisa rayas beige 2", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-jeans-ni-o-camisa-rayas-beige-2-130-5A.jpg", price: 55 },
  { name: "conjunto jeans ni o dinosaurio 2 piezas", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-jeans-ni-o-dinosaurio-2-piezas-120-4A.jpg", price: 55 },
  { name: "conjunto ni o 2 piezas oto o invierno su", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-2-piezas-oto-o-invierno-su-120-4A.jpg", price: 55 },
  { name: "conjunto ni o 2pz cocodrilo sudadera jea", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-2pz-cocodrilo-sudadera-jea-120-4A.jpg", price: 55 },
  { name: "conjunto ni o 2pz letra bordada negro su", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-2pz-letra-bordada-negro-su-90-18-24M.jpg", price: 55 },
  { name: "conjunto ni o 2pz letras sudadera", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-2pz-letras-sudadera-120-4A.jpg", price: 55 },
  { name: "conjunto ni o 2pz sudadera beige parche", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-2pz-sudadera-beige-parche-110-3A.jpg", price: 55 },
  { name: "conjunto ni o 2pz sudadera beige parche", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-2pz-sudadera-beige-parche-120-4A.jpg", price: 55 },
  { name: "conjunto ni o dinosaurio 2 piezas sudade", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-dinosaurio-2-piezas-sudade-130-5A.jpg", price: 55 },
  { name: "conjunto ni o new york u s a 2 piezas ot", cod: "110", talla: "3 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-new-york-u-s-a-2-piezas-ot-110-3A.jpg", price: 55 },
  { name: "conjunto ni o oto o 2 piezas sudadera le", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-oto-o-2-piezas-sudadera-le-120-4A.jpg", price: 55 },
  { name: "conjunto ni o polo rayas azul osito 2 pi", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-polo-rayas-azul-osito-2-pi-90-18-24M.jpg", price: 55 },
  { name: "conjunto ni o rayas 28 baseball 2 piezas", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-rayas-28-baseball-2-piezas-90-18-24M.jpg", price: 55 },
  { name: "conjunto ni o rayas negro blanco 2 pieza", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-ni-o-rayas-negro-blanco-2-pieza-130-5A.jpg", price: 55 },
  { name: "conjunto osito xisx polo jean azul 2 pie", cod: "130", talla: "5 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-osito-xisx-polo-jean-azul-2-pie-130-5A.jpg", price: 55 },
  { name: "conjunto overol beb ni o oso 2 piezas ot", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/conjunto-overol-beb-ni-o-oso-2-piezas-ot-120-4A.jpg", price: 55 },
  { name: "jean r camisa pantal n 2pzs", cod: "140", talla: "6 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/jean-r-camisa-pantal-n-2pzs-140-6A.jpg", price: 55 },
  { name: "overol de mezclilla con bordado de oso a", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/overol-de-mezclilla-con-bordado-de-oso-a-90-18-24M.jpg", price: 55 },
  { name: "polera casual de punto waffle de manga l", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/polera-casual-de-punto-waffle-de-manga-l-100-2A.jpg", price: 55 },
  { name: "polera con dise o de oso y falso denim c", cod: "120", talla: "4 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/polera-con-dise-o-de-oso-y-falso-denim-c-120-4A.jpg", price: 55 },
  { name: "polera con letras de coraz n blanco y pa", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/polera-con-letras-de-coraz-n-blanco-y-pa-100-2A.jpg", price: 55 },
  { name: "polera con rayas manga larga negro blanc", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/polera-con-rayas-manga-larga-negro-blanc-90-18-24M.jpg", price: 55 },
  { name: "polera de cuello redondo con bordado oso", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/polera-de-cuello-redondo-con-bordado-oso-90-18-24M.jpg", price: 55 },
  { name: "polera denim con mangas largas a rayas o", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/polera-denim-con-mangas-largas-a-rayas-o-100-2A.jpg", price: 55 },
  { name: "polera genial mama boys blanco y jeans a", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/polera-genial-mama-boys-blanco-y-jeans-a-100-2A.jpg", price: 55 },
  { name: "polera manga larga blanco jeans rasgado", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/polera-manga-larga-blanco-jeans-rasgado-100-2A.jpg", price: 55 },
  { name: "polera manga larga caqui 2und", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/polera-manga-larga-caqui-2und-90-18-24M.jpg", price: 55 },
  { name: "polera manga larga con cuello redondo bl", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/polera-manga-larga-con-cuello-redondo-bl-90-18-24M.jpg", price: 55 },
  { name: "polera manga larga negro 12meses", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/polera-manga-larga-negro-12meses-90-18-24M.jpg", price: 55 },
  { name: "polo de manga corta blanco y jeans negro", cod: "100", talla: "2 AÑOS", category: "jeans-nina", image: "/img/jeans-nina/polo-de-manga-corta-blanco-y-jeans-negro-100-2A.jpg", price: 55 },
  { name: "polo manga corta blanco jeans rasgado", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/polo-manga-corta-blanco-jeans-rasgado-90-18-24M.jpg", price: 55 },
  { name: "polo manga corta con cuello redondo a ra", cod: "90", talla: "18-24 Meses", category: "jeans-nina", image: "/img/jeans-nina/polo-manga-corta-con-cuello-redondo-a-ra-90-18-24M.jpg", price: 55 },
  { name: "18 24 mixxed color", cod: "90", talla: "18-24 Meses", category: "vestidos-nina", image: "/img/vestidos-nina/18-24-mixxed-color-90-18-24M.jpg", price: 55 },
  { name: "2 3 morado claro", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/2-3-morado-claro-110-3A.jpg", price: 55 },
  { name: "2 conjunto 2 piezas beb ni a fleece grue", cod: "90", talla: "18-24 Meses", category: "vestidos-nina", image: "/img/vestidos-nina/2-conjunto-2-piezas-beb-ni-a-fleece-grue-90-18-24M.jpg", price: 55 },
  { name: "2 conjunto ni a 2 piezas chaqueta manga", cod: "90", talla: "18-24 Meses", category: "vestidos-nina", image: "/img/vestidos-nina/2-conjunto-ni-a-2-piezas-chaqueta-manga-90-18-24M.jpg", price: 55 },
  { name: "2 marron caquie", cod: "100", talla: "2 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/2-marron-caquie-100-2A.jpg", price: 55 },
  { name: "2 rosa manga larga", cod: "100", talla: "2 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/2-rosa-manga-larga-100-2A.jpg", price: 55 },
  { name: "2 verde limon", cod: "100", talla: "2 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/2-verde-limon-100-2A.jpg", price: 55 },
  { name: "2 vestido lindo de malla con patchwork d", cod: "100", talla: "2 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/2-vestido-lindo-de-malla-con-patchwork-d-100-2A.jpg", price: 55 },
  { name: "2 violeta vestido de malla con parc", cod: "100", talla: "2 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/2-violeta-vestido-de-malla-con-parc-100-2A.jpg", price: 55 },
  { name: "2 y 3 verde oliva", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/2-y-3-verde-oliva-110-3A.jpg", price: 55 },
  { name: "3 conjunto 2 piezas volantes floral", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/3-conjunto-2-piezas-volantes-floral-110-3A.jpg", price: 55 },
  { name: "3 rosa vestido de princesa con flor", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/3-rosa-vestido-de-princesa-con-flor-110-3A.jpg", price: 55 },
  { name: "3 vestido casual mariposas con mo o", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/3-vestido-casual-mariposas-con-mo-o-110-3A.jpg", price: 55 },
  { name: "3 vestido con capa con lazo manga c", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/3-vestido-con-capa-con-lazo-manga-c-110-3A.jpg", price: 55 },
  { name: "3 vestido organza floral manga abul", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/3-vestido-organza-floral-manga-abul-110-3A.jpg", price: 55 },
  { name: "3 vestido peque o de tut de encaje", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/3-vestido-peque-o-de-tut-de-encaje-110-3A.jpg", price: 55 },
  { name: "3 vestido princesa preadolescente con la", cod: "110", talla: "3 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/3-vestido-princesa-preadolescente-con-la-110-3A.jpg", price: 55 },
  { name: "4 falda vestido princesa floral con", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/4-falda-vestido-princesa-floral-con-120-4A.jpg", price: 55 },
  { name: "4 rosa floreada", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/4-rosa-floreada-120-4A.jpg", price: 55 },
  { name: "4 vestido de princesa para ni as co", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/4-vestido-de-princesa-para-ni-as-co-120-4A.jpg", price: 55 },
  { name: "4 vestido de tul con lentejuelas pa", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/4-vestido-de-tul-con-lentejuelas-pa-120-4A.jpg", price: 55 },
  { name: "4 vestido elegante adornado con enc", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/4-vestido-elegante-adornado-con-enc-120-4A.jpg", price: 55 },
  { name: "4 vestido jacquard princesa sin man", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/4-vestido-jacquard-princesa-sin-man-120-4A.jpg", price: 55 },
  { name: "4 vestido ni a tweed chanel negro b", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/4-vestido-ni-a-tweed-chanel-negro-b-120-4A.jpg", price: 55 },
  { name: "4 vestido organza floral manga abul", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/4-vestido-organza-floral-manga-abul-120-4A.jpg", price: 55 },
  { name: "5 capa de princesa con brillos y ve", cod: "130", talla: "5 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/5-capa-de-princesa-con-brillos-y-ve-130-5A.jpg", price: 55 },
  { name: "5 vestido abombado de flores de bod", cod: "130", talla: "5 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/5-vestido-abombado-de-flores-de-bod-130-5A.jpg", price: 55 },
  { name: "5 vestido blanco", cod: "130", talla: "5 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/5-vestido-blanco-130-5A.jpg", price: 55 },
  { name: "5 vestido coviviky encaje dulce ni", cod: "130", talla: "5 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/5-vestido-coviviky-encaje-dulce-ni-130-5A.jpg", price: 55 },
  { name: "5 vestido de princesa color s lido", cod: "130", talla: "5 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/5-vestido-de-princesa-color-s-lido-130-5A.jpg", price: 55 },
  { name: "5 vestido dorado con cuello halter", cod: "130", talla: "5 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/5-vestido-dorado-con-cuello-halter-130-5A.jpg", price: 55 },
  { name: "5 vestido ni a blanco bordado flore", cod: "130", talla: "5 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/5-vestido-ni-a-blanco-bordado-flore-130-5A.jpg", price: 55 },
  { name: "5 vestido para ni a elegante para b", cod: "130", talla: "5 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/5-vestido-para-ni-a-elegante-para-b-130-5A.jpg", price: 55 },
  { name: "6 vestido fiesta floral manga corta", cod: "140", talla: "6 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/6-vestido-fiesta-floral-manga-corta-140-6A.jpg", price: 55 },
  { name: "crema", cod: "90", talla: "18-24 Meses", category: "vestidos-nina", image: "/img/vestidos-nina/crema-90-18-24M.jpg", price: 55 },
  { name: "rosa", cod: "90", talla: "18-24 Meses", category: "vestidos-nina", image: "/img/vestidos-nina/rosa-90-18-24M.jpg", price: 55 },
  { name: "rosa claro", cod: "90", talla: "18-24 Meses", category: "vestidos-nina", image: "/img/vestidos-nina/rosa-claro-90-18-24M.jpg", price: 55 },
  { name: "vestido chaleco gris chaqueta c", cod: "90", talla: "18-24 Meses", category: "vestidos-nina", image: "/img/vestidos-nina/vestido-chaleco-gris-chaqueta-c-90-18-24M.jpg", price: 55 },
  { name: "vestido de princesa tejido de punto azul", cod: "120", talla: "4 AÑOS", category: "vestidos-nina", image: "/img/vestidos-nina/vestido-de-princesa-tejido-de-punto-azul-120-4A.jpg", price: 55 },
  { name: "vestido princesa beb sin mangas navidad", cod: "90", talla: "18-24 Meses", category: "vestidos-nina", image: "/img/vestidos-nina/vestido-princesa-beb-sin-mangas-navidad-90-18-24M.jpg", price: 55 },
]; export default productos;
